### ISSUE TITLE
Can't find the compiled file.

### ISSUE THREAD

**Issue by fearless29** [MrEmpy/Condor#1]
Hello!
 After the compilation finished, That word.exe (in my case) can't find in Condor dir.
Where it is?

**Comment by brosck** [comment]
Hello,

Did you run it on a WSL subsystem?

**Comment by antianalysis** [comment]
Bruh i run it in WSL but still can't find it

**Comment by brosck** [comment]
I've heard reports of compilation problems. I recommend that you copy run the tool, and after the compilation message, press N, then copy the Condor directory and send it to a Windows system. Afterwards access the directory by cmd or powershell, and compile manually with command shown at compile time when it was refused.

**Comment by brosck** [comment]
I will implement a way of compiling through a Linux system, for now there is not, the best way is to do it manually.

**Comment by antianalysis** [comment]
Aren't you doing an update to fix the problem?

**Comment by brosck** [comment]
I'm still doing.

**Comment by brosck** [comment]
Problem solved.
